// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sinyal-cards/Current.tsx": () => import("../components/mockups/sinyal-cards/Current.tsx"),
  "./components/mockups/sinyal-cards/Editorial.tsx": () => import("../components/mockups/sinyal-cards/Editorial.tsx"),
  "./components/mockups/sinyal-cards/Glass.tsx": () => import("../components/mockups/sinyal-cards/Glass.tsx"),
  "./components/mockups/sinyal-cards/Minimal.tsx": () => import("../components/mockups/sinyal-cards/Minimal.tsx")
};
